name: Release

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - master
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Generate Version Tag and GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

  build-docs:
    needs: release
    runs-on: ubuntu-latest
    if: ${{ needs.release.result == 'success' }}
    name: Generate and Upload Documentation
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci
      - run: npm run docs
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy-docs:
    needs: build-docs
    runs-on: ubuntu-latest
    name: Deploy Docs to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
